# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef989c6aba8033317309e2205eeab99ae43738c8e1a6c0d2026cf1a10384c30ae9d9758614fedd7500609db8f9b7163913ffea977ce67a6e4fcabe257d654847

test:
  secret_key_base: 5bbb74440982fdef50a72383f840acd51d710fe53191a1a03b9c1f738c3b6c8f1a7fde09d9ed1c65fc02085e80fc3bf06cf45f5d07610e76e66d9fd3e30ea667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
